### ISSUE TITLE
Release Trains

### ISSUE THREAD

**Issue by gr2m** [gr2m/milestones#1]
- [x] setup unified release workflows for all Hoodie modules
  - [ ] [deferred https://github.com/hoodiehq/hoodie.js/issues/337] hoodie.js
  - [x] hoodie-cli
  - [ ] [deferred] https://github.com/hoodiehq/hoodie-cli/issues/121 my-first-hoodie
  - [x] hoodie-plugin-appconfig
  - [x] hoodie-plugin-email
  - [x] hoodie-plugin-users
  - [x] hoodie-plugins-manager
  - [x] hoodie-plugins-api
  - [x] hoodie-server
  - [x] hoodie-pocket-UIKit
  - [x] node-multicouch
  - [x] couchdb-db-notify
  - [x] pocket
  - [ ] [deferred https://github.com/hoodiehq/hoodie.admin.js/issues/4] hoodie-admin.js
  - [x] local-tld-lib
  - [x] node-ports
- [x] for any Hoodie Module release, update `my-first-hoodie` dependencies
