### ISSUE TITLE
Migrate To PouchDB

### ISSUE THREAD

**Issue by gr2m** [gr2m/milestones#12]
see also hoodiehq/hoodie.js#8

- [ ] https://github.com/hoodiehq/hoodie.js/issues/8 Migrate To PouchDB
- [x] #10 Refactor hoodie.js
- [x] #11 returning standard-compliant promise
- [x] #29 replace Backbone Events with EventEmitter
- [x] #30 merge hoodie.store & hoodie.remote

**Comment by gr2m** [comment]
Splitting this up in more issues
