### ISSUE TITLE
build new hoodie-app-something-tracker (was: my-first-hoodie)

### ISSUE THREAD

**Issue by gr2m** [gr2m/milestones#32]
- [x] define idea for new hoodie-app-template  
  the new MFH will be a tracking app, where you can track any type of information you'd like (financials, training etc). It's basically very similar to the todo app, but just another use case. 
- [x] create new repo [hoodie-app-something-tracker](https://github.com/hoodiehq/hoodie-app-something-tracker) (take code from https://github.com/hoodiehq/my-first-hoodie/tree/something-tracker)
- [x] implement new hoodie-app-something-tracker

**Comment by zoepage** [comment]
Team Tessie will take care of this task.

**Comment by gr2m** [comment]
Good enough for now :)
