### ISSUE TITLE
Launch documentation

### ISSUE THREAD

**Issue by gr2m** [gr2m/milestones#7]
- [x] update hoodie-plugin-template hoodiehq/documentation/issues/12
- [x] Hoodie Concepts hoodiehq/documentation/issues/41
- [x] my-first-plugin (plugin development) hoodiehq/documentation/issues/40
- [x] email plugin hoodiehq/documentation/issues/37
- [x] synchronisation hoodiehq/documentation/issues/35
- [x] Storage hoodiehq/documentation/issues/34
- [x] Account Module hoodiehq/documentation/issues/33
- [x] prerequisites / system requirements / browser compatibilities hoodiehq/documentation/issues/32
- [x] getting started with Hoodie (installation guide) hoodiehq/documentation/issues/32
- [x] Hoodie Magic hoodiehq/documentation/issues/45
- [x] add more content to FAQ https://github.com/hoodiehq/faq
- [x] contributor onboarding hoodiehq/documentation/issues/65
- [x] IRC Office Hours /hoodiehq/documentation/blob/gh-pages/tutorials/irc-office-hours.md
- [x] upload Cheat Sheet (see http://hood.ie/intro#get-started)
- [x] set up "How to give a Hoodie Workshop" https://github.com/hoodiehq/documentation/blob/gh-pages/tutorials/hosting-a-hoodie-workshop.md
- [x] deployments of *.hood.ie pages hoodiehq/documentation/issues/64
- [x] my-first-hoodie hoodiehq/documentation/issues/11
- [x] docker hoodiehq/documentation/issues/10
- [x] User Registration Flow hoodiehq/documentation/issues/7
- [x] glossary of Hoodie terms hoodiehq/documentation/blob/gh-pages/glossary.md
- [x] document deployments hoodiehq/documentation/issues/24
- [x] user plugin hoodiehq/documentation/issues/38
- [x] shares hoodiehq/documentation/issues/36
- [x] Figure out translations hoodiehq/documentation/issues/22
